#:import random random.random

ShowcaseScreen:
    name: 'OlSa'
    fullscreen: True
    on_parent: app.showcase_gridlayout(grid)
    CGridLayout:
        id: grid  
        size_hint: (1, 1)
        
<CGridLayout@GridLayout+BackgroundColor>

<BackgroundColor@Widget>
    pos_hint: {'center_x': .5, 'center_y': .5}
    size_hint: .9, .9
    canvas.before:
        Color:
            rgba: .2, .3, .4, 1
        Rectangle:
            size: self.size
            pos: self.pos
